#!/usr/bin/env python3
"""Merge data/part1..4.json (produced by research) into data/prizes.js as
window.NOBEL_DATA. Validates schema lightly and reports gaps."""
import json, os, sys, glob

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")

REQUIRED = ["id", "year", "subfield", "categories", "tags"]

def main():
    merged = []
    parts = sorted(glob.glob(os.path.join(DATA, "part*.json")))
    if not parts:
        print("No part*.json files found yet.")
        return 1
    for p in parts:
        with open(p) as f:
            arr = json.load(f)
        if not isinstance(arr, list):
            print(f"!! {p} is not a JSON array"); return 1
        merged.extend(arr)
        print(f"  {os.path.basename(p)}: {len(arr)} entries")

    # de-dupe by id, keep last
    by_id = {}
    for e in merged:
        by_id[e.get("id")] = e
    out = sorted(by_id.values(), key=lambda e: (e.get("year", 0), e.get("id", "")))

    # light validation
    years = {}
    for e in out:
        for r in REQUIRED:
            if e.get("awarded", True) and r not in e:
                print(f"  WARN {e.get('id')}: missing {r}")
        years[e.get("year")] = years.get(e.get("year"), 0) + 1

    awarded = [e for e in out if e.get("awarded", True)]
    print(f"\nTotal entries: {len(out)} ({len(awarded)} awarded)")
    yr = [e['year'] for e in awarded]
    if yr:
        print(f"Year range: {min(yr)}–{max(yr)}")

    js = "/* Auto-generated by build_data.py — do not edit by hand. */\n"
    js += "window.NOBEL_DATA = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n"
    with open(os.path.join(DATA, "prizes.js"), "w") as f:
        f.write(js)
    print(f"Wrote data/prizes.js ({len(js)} bytes)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
